ISA_cfa_plugin.py: explicitly treat all command output as utf-8
Python3 returns output as byte strings. We need to decode that first
before we can work with the output as normal strings. For example,
without this change the following error occurs for
'"symlink" in file_type':
  TypeError: Type str doesn't support the buffer API

Assuming that the output is utf-8 encoded is a simplification,
but should be a safe bet (also works for plain ASCII).

Signed-off-by: Patrick Ohly <patrick.ohly@intel.com>